### ISSUE TITLE
C++ virtual function dispatch efficiency?

### ISSUE THREAD

**Issue by ilg-ul** [riscv/riscv-eabi-spec#3] opened 2019-05-25 20:52 UTC
In my initial EABI proposal I have a notice to check if the register allocation matches the needs of C++ virtual function dispatch, notice that I pass here too.

I think that this is a feature of C++ that requires a careful implementation.

**Comment by kasanovic** [comment] 2019-08-29 00:38
I believe this was also confirmed, so closing this issue.

**Closed as completed by kasanovic** 2019-08-29 00:38 UTC

**Comment by jnk0le** [comment] 2022-07-24 22:07
@ilg-ul 
did some analysis and I think it's even possible to do virtual function dispatch without any T and S registers at full pressure on A

https://godbolt.org/z/MM3c97Eos

<details>
  <summary>main2 modified for this case</summary>
 
  ```
  main2(int, int, int, int, int, int, int, int):
        addi    sp,sp,-32 // 16 is enough
        sw      ra,28(sp)
        sw      a7,0(sp)
        mv      a7,a6
        mv      a6,a5
        mv      a5,a4
        mv      a4,a3
        mv      a3,a2
        mv      a2,a1
        mv      a1,a0
        lui     a0,%hi(rrr) //load *this
        lw      a0,%lo(rrr)(a0) // normally addi, here we handle pointer
        lw      ra,0(a0) // start virtual stuff
        lw      ra,0(ra)
        jalr    ra,0(ra)
       // shouldn't there be something???
       // like 
       // lw      ra,28(sp)
       // addi    sp,sp,32
       // jr      ra
  ```
  
</details>

- according to table 2.1 in riscv spec  `jalr ra, 0(ra)` is ok, ~but `jalr x0, 0(ra)` used for tail chaining, probably wreaks havoc in branch predictors~
- this construct is inefficient even on many of the simplest pipelines
- one less mov so maybe better on simplest things like serv etc.
- generic riscv target in gcc has load to use latency modeled, so that mov is "cheaper" than serializing virtual dispatch


<details>
  <summary>main2 with just one T register</summary>
 
  ```
  main2(int, int, int, int, int, int, int, int):
        addi    sp,sp,-32 // 16 is enough
        sw      ra,28(sp)
        lui     ra,%hi(rrr) //load *this
        lw      ra,%lo(rrr)(ra) // normally addi, here we handle pointer
        sw      a7,0(sp)
        mv      a7,a6
        lw      t0,0(ra) // start virtual stuff
        mv      a6,a5
        mv      a5,a4
        lw      t0,0(t0)
        mv      a4,a3
        mv      a3,a2
        mv      a2,a1
        mv      a1,a0
        mv      a0,ra
        jalr    ra,0(t0)
        // shouldn't there be something???
        // like 
        // lw      ra,28(sp)
        // addi    sp,sp,32
        // jr      ra
  ```
  
</details>

- here we have properly handled load latencies and ~bogus tailchaining.~
- compilers seem to tend to treat ra as an immutable register (at least for data processing), so here we get to that "at least 2 T registers needed for virtual dispatch"

**Comment by kito-cheng** [comment] 2022-07-25 02:57
```
     // shouldn't there be something???
     // like 
     // lw      ra,28(sp)
     // addi    sp,sp,32
     // jr      ra
```
Seems like both GCC and clang generate function epilogue without stack adjust when there is no return value for a non-void function, I saw GCC emit a __builtin_unreachable() at end of function for that situation - then nothing guarantee correct :P
(NOTE: The logic behind that is compiler might generate anything when it's undefined behavior)
 
After changing return type of main2 to void, code gen back to expected behavior. 
https://godbolt.org/z/xfTYeeoGM

**Comment by jnk0le** [comment] 2022-07-25 07:35
shouldn't that UB be related to just content of returned variable? As is the most obvious and expected scenario.

**Comment by jnk0le** [comment] 2022-07-25 16:40
correction: tail chaining is not possible with 0 T regs, and again inefficient with 1 T register

**Comment by jnk0le** [comment] 2022-07-26 20:43
more interesting is that this UB is no different than `__attribute__((noreturn))`, the prologue spills are still there in either case.

`while(1);` seems to be broken in clang 13+. https://godbolt.org/z/rbTabW8oW
